/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class arsic_aleksa_chatapplication_MyNDK */

#ifndef _Included_arsic_aleksa_chatapplication_MyNDK
#define _Included_arsic_aleksa_chatapplication_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     arsic_aleksa_chatapplication_MyNDK
 * Method:    encryptDecryptMessage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_arsic_aleksa_chatapplication_MyNDK_encryptDecryptMessage(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
